language: python
env: PYTHONPATH='.'
services:
  - mongodb
python:
  - "3.4"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libfuse-dev
  - sudo apt-get install -y libattr1-dev
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
script:
  py.test --cov fusegridfs tests
after_success:
  coveralls
